### ISSUE TITLE
Frequently Asked Questions (FAQ) / helpful tricks

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#225]
- [x] Add label `good first issue` automatically to Wiki documentation
_____
Additionally
- [x] Connection parameters (https://github.com/Zefau/ioBroker.jarvis/issues/349)
- [x] base64-Wert als Icons (https://github.com/Zefau/ioBroker.jarvis/issues/348)
- [x] ~~2 Instanzen~~ (siehe Connection parameters https://github.com/Zefau/ioBroker.jarvis/issues/349)
- [x] by Modules
  - [x] AdapaterStatus Whitelist/Blacklist (https://github.com/Zefau/ioBroker.jarvis/issues/323)

**Comment by Zefau** [comment]
Documentation added with `v1.1.0-beta.108`, see https://github.com/Zefau/ioBroker.jarvis/wiki/de-FAQ.
