### ISSUE TITLE
Layout configuration

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#637]
- [x] Introduce tiles #235
- [x] Introduce different widget sizes #277 
- [x] Widget "Buttons" #333 
- [x] Add navigation drawer #81 
- [x] Flexible Layout: Allow lines in tabs #118 
- [x] ~~Combine different modules within a single widget #127~~
- [x] Flexible Layout: Allow Widgets to span accross columns #129 
- [x] Allow TopBar / TabBar to be placed top, bottom, left or right #234 
- [x] Dropdown Menü für Button in der TAB-Leiste #638
- [x] Optimize mobile layout and margins #595

**Comment by smile-albion** [comment]
Vielleicht könnte man an dieser Stelle noch die Farben der Widget Käste mit aufnehmen?
--> Farbe generell festlegen oder Farbe je nach State bestimmter Werte ändern. Siehe analog zu Habpanel:
![1611006909117-habpanel-mozilla-firefox-2021-01-18-22 54 31](https://user-images.githubusercontent.com/79671143/109564421-5491be80-7ae1-11eb-88c8-284ad53483c7.png)
iobroker Post: https://forum.iobroker.net/post/561770
